---
# roles/xdrive/handlers/main.yml

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart xdrive driver
  ansible.builtin.systemd:
    name: "{{ xdrive_driver_service_name }}"
    state: restarted
  when: xdrive_run_driver | bool

- name: Restart joy to twist
  ansible.builtin.systemd:
    name: "{{ xdrive_joy_service_name }}"
    state: restarted
  when: xdrive_run_joy_to_twist | bool

- name: Restart local teleop
  ansible.builtin.systemd:
    name: "{{ xdrive_local_service_name }}"
    state: restarted
  when: xdrive_run_local_teleop | bool

- name: Restart revhub
  ansible.builtin.systemd:
    name: "{{ xdrive_revhub_service_name }}"
    state: restarted
  when: xdrive_run_revhub | bool

- name: Restart motion control
  ansible.builtin.systemd:
    name: "{{ xdrive_motion_service_name }}"
    state: restarted
  when: xdrive_run_motion_control | bool
